import { MessageSquare, ShieldAlert, Video, FileText, Type, Activity, Key, BarChart3, Users, Server, Sparkles, BrainCircuit } from "lucide-react";

const features = [
  {
    icon: <MessageSquare className="w-6 h-6" />,
    title: "Real-time Messaging",
    description: "Sub-50ms latency using Socket.IO for seamless and instantaneous communication."
  },
  {
    icon: <ShieldAlert className="w-6 h-6 text-error" />,
    title: "AI-powered Moderation",
    description: "Automatic toxicity detection and content filtering powered by Groq and FastAPI."
  },
  {
    icon: <Video className="w-6 h-6 text-info" />,
    title: "Voice & Video Calling",
    description: "Crystal clear WebRTC integration using ZegoCloud for high-quality meetings."
  },
  {
    icon: <FileText className="w-6 h-6 text-warning" />,
    title: "File Sharing",
    description: "Secure and optimized media uploads managed by Cloudinary infrastructure."
  },
  {
    icon: <Type className="w-6 h-6 text-primary" />,
    title: "Typing Indicators",
    description: "Real-time presence and typing events distributed via Redis Pub/Sub."
  },
  {
    icon: <Activity className="w-6 h-6 text-success" />,
    title: "Presence Tracking",
    description: "Accurate online/offline status synchronized across all connected devices."
  },
  {
    icon: <Key className="w-6 h-6" />,
    title: "JWT Authentication",
    description: "Stateless, secure token-based authentication with automatic refresh cycles."
  },
  {
    icon: <BarChart3 className="w-6 h-6 text-secondary" />,
    title: "Admin Analytics",
    description: "Comprehensive dashboards for monitoring system health and user activity."
  },
  {
    icon: <Users className="w-6 h-6 text-accent" />,
    title: "Role-based Access",
    description: "Granular permissions for users, moderators, and system administrators."
  },
  {
    icon: <Server className="w-6 h-6" />,
    title: "Horizontal Scaling",
    description: "Stateless backend architecture designed to scale across multiple instances."
  },
  {
    icon: <Sparkles className="w-6 h-6 text-warning" />,
    title: "Smart Replies",
    description: "Context-aware response suggestions generated by integrated LLMs."
  },
  {
    icon: <BrainCircuit className="w-6 h-6 text-primary" />,
    title: "ML Intent Detection",
    description: "Advanced natural language processing for intelligent message routing."
  }
];

const FeatureGrid = () => {
  return (
    <section id="features" className="py-24 bg-base-200/50">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl font-bold text-base-content mb-4">Everything you need to build communities</h2>
          <p className="text-base-content/70 text-lg">
            PASO provides a comprehensive suite of tools designed for scale, security, and exceptional user experience.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <div 
              key={index} 
              className={`bg-base-100 rounded-2xl p-6 border border-base-200 group card-anim ${index % 2 === 0 ? 'animate-soft-tilt hover-glow' : 'animate-soft-tilt-reverse hover-glow-reverse'}`}
            >
              <div className="w-12 h-12 rounded-lg bg-base-200 flex items-center justify-center mb-4 group-hover:bg-primary/10 group-hover:text-primary transition-colors">
                {feature.icon}
              </div>
              <h3 className="text-lg font-bold text-base-content mb-2">{feature.title}</h3>
              <p className="text-sm text-base-content/70 leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeatureGrid;
